Add: List of hex-codes
amos-kibet/hex-code-generator pull request #2
Opened 2021-10-23 13:46 UTC by PROxZIMA

Creates an array of 0..16777216, maps them to hex string and adds
padding to them

2021-10-23 13:50 UTC, amos-kibet commented
Thanks, I'll have a look once I'm on my laptop and merge it.

2021-10-27 14:44 UTC, amos-kibet requested changes
All look good. You're smart, I like how you have used padStart method. I had never heard of it before

2021-10-27 14:44 UTC, amos-kibet commented on app.js
> +console.log('hi');
Delete this console message

2021-10-28 03:00 UTC, PROxZIMA commented on app.js
> +console.log('hi');
Done!

2021-10-28 03:26 UTC, PROxZIMA commented
Haha! It just converts `256*256*256` integers to `hex` and then left pad them with `0`

2021-10-28 07:49 UTC, amos-kibet commented
What I read is that with padStart(x, y), the x parameter specifies the length of the resulting value after 'trimming', while the y parameter replaces the 'trimmed' values. So, I was expecting all your 'trimmed' values will be replaced with 0, then they were not. Maybe you can explain a little how that method works.

Otherwise, your solution is great. Your programmatic approach is incredible.

2021-10-28 07:50 UTC, merged

2021-10-28 09:14 UTC, PROxZIMA commented
Not exactly trimming. According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart)
> The padStart() method pads the current string with another string (multiple times, if needed) until the resulting string reaches the given length. The padding is applied from the start of the current string.

So if `i` is `15`, it's hex string will be `f` and it will be padded with `0` until it's length becomes `6`, resulting `00000f`. That's all

2021-10-29 18:31 UTC, amos-kibet commented
I think I will read and practice  more on it to understand it better.
It was nice interacting with you sir. If I may ask, could we collaborate more? I'm self-teaching coding and preparing to transition from electrical field to software. I could use your skills as we collaborate. If this sounds great to you, we could talk about objectives, projects we could build together, and learnings we could take.

2021-10-30 03:55 UTC, PROxZIMA commented
Hey don't call me sir!! I'm still an under graduate.
> If I may ask, could we collaborate more?

Sure I would love to work with you. As I'm still learning stuffs using them in an actual project will be beneficial

2021-10-30 18:57 UTC, amos-kibet commented
Sir is a polite and respectful way of addressing a man, but that is noted. Do you have projects we can collaborate on building?

2021-10-31 02:35 UTC, PROxZIMA commented
I'm not actually learning web development but it's my hobby so I have one
https://github.com/PROxZIMA/prism
This a simple start-page I forked from [Prismatic Night](https://github.com/3r3bu5x9/Prismatic-Night). Still have tons of work remaining.

If you have anything from your side then I'm glad to hear!!